server:
  port: 25000

spring:
  application:
    name: gulimall-seckill
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      enabled: false
  redis:
    host: localhost
    port: 6379
  rabbitmq:
    host: localhost
    port: 5672
    virtual-host: /
    username: guest
    password: guest
  thymeleaf:
    cache: false
  session:
    store-type: redis
  # 异步任务线程池（@Async 使用）
  task:
    execution:
      pool:
        core-size: 5
        max-size: 50

feign:
  sentinel:
    enabled: false

management:
  endpoints:
    web:
      exposure:
        include: '*'
