upstream gulimall {
    server 192.168.3.43:88;
}

server {
    listen       80;
    server_name  gulimall.com *.gulimall.com;

    location / {
        root   /usr/share/nginx/html;
        try_files $uri $uri/ /index.html;
    }

    location /static/ {
        root   /usr/share/nginx/html;
    }

    location /payed/ {
        proxy_set_header Host order.gulimall.com;
        proxy_pass http://gulimall;
    }

    location /api/ {
        proxy_set_header Host $host;
        proxy_pass http://gulimall;
    }
}